from django.urls import path
from .views import (
    RegisterCreatorUserView, DeleteCreatorUserView,
    RegisterBusinessUserView, DeleteBusinessUserView,
    CreatorUserLoginView, BusinessUserLoginView,
    UserDetailView, LogoutView,
    CreatorUserProfileView, BusinessUserProfileView,
    UserSearchView, ProfileView,
    FollowUserView, UnfollowUserView,
    IsFollowingView, NotificationListView,
    MarkNotificationAsReadView, GetAllUsersView,
    SendOTPView, VerifyOTPView,
    PasswrdResetRequestView, PasswordResetConfirmView,
    BusinessSearchView
)

urlpatterns = [
    path('', UserDetailView.as_view(), name='user-detail'),
    path('register/creator/', RegisterCreatorUserView.as_view(),name='register-creator'),
    path('delete/creator/', DeleteCreatorUserView.as_view(), name='delete-creator'),
    path('register/business/', RegisterBusinessUserView.as_view(),name='register-business'),
    path('delete/business/', DeleteBusinessUserView.as_view(), name='delete-business'),
    path('login/creator/', CreatorUserLoginView.as_view(), name='login-creator'),
    path('login/business/', BusinessUserLoginView.as_view(), name='login-business'),
    path('logout/', LogoutView.as_view(), name="user-logout"),
    path('profile/creator/', CreatorUserProfileView.as_view(),name='creator-profile'),
    path('profile/business/', BusinessUserProfileView.as_view(),name='business-profile'),
    path('search/', UserSearchView.as_view(), name='user-search'),
    path('search-business/', BusinessSearchView.as_view(), name='business-search'),
    path('profiles/<str:username>', ProfileView.as_view(), name='profile'),
    path('profiles/<str:username>/follow/', FollowUserView.as_view(), name='follow-user'),
    path('profiles/<str:username>/unfollow/', UnfollowUserView.as_view(), name='unfollow-user'),
    path('profiles/<str:username>/is_following/', IsFollowingView.as_view(), name='is-following'),
    path('notifications/', NotificationListView.as_view(), name='notifications'),
    path('notifications/<int:pk>/mark_as_read/', MarkNotificationAsReadView.as_view(), name='mark-notification-as-read'),
    path('users/', GetAllUsersView.as_view(), name='get-all-creators'),
    path('otp/send/', SendOTPView.as_view(), name='send-otp'),
    path('otp/verify/', VerifyOTPView.as_view(), name='verify-otp'),
    path('password-reset/', PasswrdResetRequestView.as_view(), name='password-reset'),
    path('password-reset-confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password-reset-confirm'),
]
