server {
    server_name api.cloutgrid.com;
    client_max_body_size 50M;

    location /.well-known/acme-challenge/ {
        alias /var/www/certbot/.well-known/acme-challenge/;
        try_files $uri =404;
    }

    location / {
        proxy_pass http://backend:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /ws/ {
        proxy_pass http://backend:8000;
        
        # Tells Nginx to switch from standard HTTP/1.0 to HTTP/1.1 for streaming
        proxy_http_version 1.1;
        
        # Crucial headers that upgrade the connection from an HTTP request to a persistent WebSocket pipe
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        
        # Pass client security details to Django Channels
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # Extends timeouts to 24 hours so Nginx doesn't kill connections if users stop typing
        proxy_read_timeout 86400s;
        proxy_send_timeout 86400s;
    }

    location /static/ {
        alias /var/www/backend/static/;
    }

    location /media/ {
        alias /var/www/backend/media/;
    }

    listen 443 ssl;
    ssl_certificate /etc/letsencrypt/live/cloutgrid.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/cloutgrid.com/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
}

server {
    listen 80;
    server_name api.cloutgrid.com;
    return 301 https://$host$request_uri;
}
