# Generated by Django 5.0.7 on 2024-07-22 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('company_website', models.URLField()),
                ('medium', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('youtube', 'Youtube')], max_length=50)),
                ('due_date', models.DateField()),
                ('requirements', models.TextField()),
                ('target_creator', models.CharField(choices=[('art', 'Art and Photography'), ('automotive', 'Automotive'), ('beauty', 'Beauty and Makeup'), ('business', 'Business'), ('diversity', 'Diversity and Inclusion'), ('education', 'Education'), ('entertainment', 'Entertainment'), ('fashion', 'Fashion'), ('finance', 'Finance'), ('food', 'Food and Beverage'), ('gaming', 'Gaming'), ('health', 'Health and Wellness'), ('home', 'Home and Gardening'), ('outdoor', 'Outdoor and Nature'), ('parenting', 'Parenting and Family'), ('pets', 'Pets'), ('sports', 'Sports and Fitness'), ('technology', 'Technology'), ('travel', 'Travel'), ('videography', 'Videography')], max_length=50)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='job_photos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.businessuser')),
            ],
        ),
    ]
