# Generated by Django 5.0.7 on 2024-09-27 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_remove_job_photo_job_applicants'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='questions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='company_website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='medium',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('youtube', 'Youtube')], max_length=10),
        ),
        migrations.AlterField(
            model_name='job',
            name='target_creator',
            field=models.CharField(choices=[('art', 'Art and Photography'), ('automotive', 'Automotive'), ('beauty', 'Beauty and Makeup'), ('business', 'Business'), ('diversity', 'Diversity and Inclusion'), ('education', 'Education'), ('entertainment', 'Entertainment'), ('fashion', 'Fashion'), ('finance', 'Finance'), ('food', 'Food and Beverage'), ('gaming', 'Gaming'), ('health', 'Health and Wellness'), ('home', 'Home and Gardening'), ('outdoor', 'Outdoor and Nature'), ('parenting', 'Parenting and Family'), ('pets', 'Pets'), ('sports', 'Sports and Fitness'), ('technology', 'Technology'), ('travel', 'Travel'), ('videography', 'Videography')], max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
