# Generated by Django 5.0.7 on 2024-11-18 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_remove_job_applicants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='company_website',
        ),
    ]
