# Generated by Django 5.0.7 on 2024-09-27 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(default='default_profile.png', upload_to='profile_pics'),
        ),
    ]
