# Generated by Django 5.0.7 on 2024-12-29 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
        ('users', '0005_alter_user_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='collaboration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collaborations', to='users.businessuser'),
        ),
    ]
